#server:
#  port: 7000
#
#spring:
#  datasource:
#    username: root
#    password: root
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://172.29.134.130:3306/mall_sms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#  global-config:
#    db-config:
#      id-type: auto
#  mapper-locations: classpath:/mapper/**/*.xml
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

#coupon:
#  user:
#    name: 123
#    age: 1